// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXynjWtERlJ73ybMw7TppyhRCHn2j9m-s',
    appId: '1:200021387061:web:9d5ae5c992eab3ccc30e7c',
    messagingSenderId: '200021387061',
    projectId: 'e-commerce-3c01a',
    authDomain: 'e-commerce-3c01a.firebaseapp.com',
    storageBucket: 'e-commerce-3c01a.firebasestorage.app',
    measurementId: 'G-X6RMY20M7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMtSrPbYhiyoVwRyA6_TwbstwMEvXyAo8',
    appId: '1:200021387061:android:570aed7e84dd66c3c30e7c',
    messagingSenderId: '200021387061',
    projectId: 'e-commerce-3c01a',
    storageBucket: 'e-commerce-3c01a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRUGxfvlMHtdaHB5vcx4Fp5TAiOBwK9Q',
    appId: '1:200021387061:ios:23812d583ca9617dc30e7c',
    messagingSenderId: '200021387061',
    projectId: 'e-commerce-3c01a',
    storageBucket: 'e-commerce-3c01a.firebasestorage.app',
    iosClientId: '200021387061-o9mdo3v92m1b29p7mt6lqa7t2vhfafcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXynjWtERlJ73ybMw7TppyhRCHn2j9m-s',
    appId: '1:200021387061:web:577817fb59ff70b9c30e7c',
    messagingSenderId: '200021387061',
    projectId: 'e-commerce-3c01a',
    authDomain: 'e-commerce-3c01a.firebaseapp.com',
    storageBucket: 'e-commerce-3c01a.firebasestorage.app',
    measurementId: 'G-PYWSYRZ8H3',
  );
}
